version: 2
jobs:
  release:
    docker:
      - image: circleci/golang:latest
    steps:
      - checkout
      - run: cd vault && curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
